<?php
/**
 * @file
 * Apigee Google tag manager.
 * 
 * Adds the google tag manager script to administration pages.
 */

/**
 * Implements hook_init().
 */
function apigee_gtm_init() {
  // Short circuit if we are not on an admin page.
  // Allow all users to be tracked
  /*if (!path_is_admin(current_path())) {
    return;
  }*/

  // Default values.
  $build_version = '';
  $mail = $GLOBALS['user']->mail;

  if (function_exists('devconnect_default_org_config')) {
    $config = devconnect_default_org_config();
    $orgname = $config->orgName;
  }
  else {
    $orgname = '';
  }

  // Modern builds have the build version set as the apigee profile version.
  if (variable_get('install_profile') == 'apigee') {
    $info = drupal_parse_info_file(drupal_get_path('profile', 'apigee') . '/apigee.info');
    if (array_key_exists('version', $info) && !empty($info['version'])) {
      $build_version = $info['version'];
    }
  }
  if (empty($build_version)) {
    // The following is mostly copypasta from devconnect.module.
    $build_info = FALSE;
    if (file_exists(DRUPAL_ROOT . '/buildInfo')) {
      $build_info = DRUPAL_ROOT . '/buildInfo';
    }
    elseif (file_exists(DRUPAL_ROOT . '/profiles/apigee/buildInfo')) {
      $build_info = DRUPAL_ROOT . '/profiles/apigee/buildInfo';
    }
    if ($build_info) {
      $fp = fopen($build_info, 'r');
      $line = trim(fgets($fp));
      fclose($fp);
      if (preg_match('!([0-9.]{2,})$!', $line, $matches)) {
        $build_version = $matches[1];
      }
    }
  }

  $data_layer = array(
    array(
      'event' => 'gtm.js',
      'gtm.start' => intval(microtime(TRUE) * 1000),
      'organization.name' => $orgname,
      'pantheon.env' => isset($_ENV['PANTHEON_ENVIRONMENT']) ? $_ENV['PANTHEON_ENVIRONMENT'] : '',
      'pantheon.site' => isset($_ENV['PANTHEON_SITE_NAME']) ? $_ENV['PANTHEON_SITE_NAME'] : '',
      'user.email' => $mail,
      'webapp.name' => 'devportal',
      'webapp.version' => $build_version,
    ),
  );
  if (array_key_exists('aac_session', $_SESSION) && array_key_exists('uuid', $_SESSION['aac_session'])) {
    $data_layer[0]['user.uuid'] = $_SESSION['aac_session']['uuid'];
  }

  if (strtolower(substr($mail, -11)) == '@apigee.com') {
    $data_layer[0]['user.internal'] = 'internal';
  }

  drupal_add_js('var dataLayer = ' . json_encode($data_layer) . ';', 'inline');
  drupal_add_js(drupal_get_path('module', 'apigee_gtm') . '/apigee_gtm.js', 'file');
}
