<?php
/**
 * @file
 * Code for the default custom blocks for the FHIR developer portal
 */

/**
 * Implements hook_block_info().
 */
function fhir_blocks_block_info(){
  $blocks = array();

  $blocks['fhir_get_started'] = array(
    'info' => t('Fhir Get Started'),
  );
  $blocks['fhir_apis_sandox'] = array(
    'info' => t('Fhir Apis and Sandbox'),
  );
  $blocks['fhir_app_gallery'] = array(
    'info' => t('Fhir App Gallery'),
  );
  $blocks['fhir_copyright'] = array(
    'info' => t('Fhir Copyright'),
  );
  $blocks['fhir_social_bottom'] = array(
    'info' => t('Fhir Social Bottom'),
  );
  $blocks['fhir_logo_caption'] = array(
    'info' => t('Fhir Logo Caption'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function fhir_blocks_block_view($delta = ''){
  $block = array();
  switch ($delta) {
    case 'fhir_get_started':
      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => theme('fhir_get_started'),
      );
      break;

    case 'fhir_apis_sandox':
      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => theme('fhir_apis_sandox'),
      );
      break;

    case 'fhir_app_gallery':
      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => theme('fhir_app_gallery'),
      );
      break;

    case 'fhir_copyright':
      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => theme('fhir_copyright'),
      );
      break;

    case 'fhir_social_bottom':
      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => theme('fhir_social_bottom'),
      );
      break;

    case 'fhir_logo_caption':
      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => theme('fhir_logo_caption'),
      );
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function fhir_blocks_theme($existing, $type, $theme, $path){
  $template_path = drupal_get_path('module', 'fhir_blocks') . '/templates';
  $items = array();
  $items['fhir_get_started'] = array(
    'template' => 'fhir_get_started',
    'path' => $template_path,
  );
  $items['fhir_apis_sandox'] = array(
    'template' => 'fhir_apis_sandox',
    'path' => $template_path,
  );
  $items['fhir_app_gallery'] = array(
    'template' => 'fhir_app_gallery',
    'path' => $template_path,
  );
  $items['fhir_copyright'] = array(
    'template' => 'fhir_copyright',
    'path' => $template_path,
  );
  $items['fhir_social_bottom'] = array(
    'template' => 'fhir_social_bottom',
    'path' => $template_path,
  );
  $items['fhir_logo_caption'] = array(
    'template' => 'fhir_logo_caption',
    'path' => $template_path,
  );
  return $items;
}
